#include <QDir>
#include <QDirIterator>
#include <QFile>
#include <QFileInfo>
#include <QRegularExpression>
#include <QSet>
#include <QTemporaryDir>
#include <QTextStream>
#include <QtTest>

#include <algorithm>

#include "DomainHeaderInventory.h"

using namespace Qt::StringLiterals;

// Standing guard against the exact class of bug the cumulative reviews on
// issue #19/PR #20 kept re-finding across rounds: a public response/request
// encoder silently bypassing the resource-limit/duplicate-key/embedded-
// Undefined/lone-surrogate invariants Value::toExactQJson()/
// toExactQJsonObject()/toExactQJsonArray() (RawJson.h) enforce.
//
// Earlier versions of this test tried to police that by pattern-matching
// specific *shapes* a lossy encoder's body might take, and then tried
// exempting three whole header files (RawJson.h/JsonDecode.h/
// AuthModels.h) by basename from an otherwise-unconditional "no
// Qt-JSON-returning declaration" scan. Every round found either a new
// declaration shape the matcher didn't cover, or -- most recently -- a
// concrete way the whole-file exemption itself could be silently
// exploited: flip RawJson.h's private lossy conversion method to public,
// add a brand-new nested header under src/ that a non-recursive
// directory listing never visits, add a conversion-operator declaration
// (a shape the return-type regex never matched), or hide a banned return
// type behind a `#define`-based alias. All four passed the previous
// version of this test unchanged.
//
// This version closes each of those four specific gaps structurally
// rather than by growing another return-type-shape regex:
//
//   1. Value::toLossyQJsonForTestingOnly() no longer exists anywhere in
//      this production header/target at all -- public or private. It has
//      been relocated to tests/RawJsonLossyTestOnly.h (a header never
//      added to the arkham_foundation production target -- see
//      CMakeLists.txt) as a free function RawJson.h grants friendship to
//      by exact qualified name, not by a whole-class friend grant. There
//      is no access specifier left in RawJson.h to flip.
//   2. The header inventory scanned below (arkhamDomainHeaderInventory(),
//      generated by CMakeLists.txt's configure_file() from the exact
//      ARKHAM_FOUNDATION_HEADERS list add_library(arkham_foundation ...)
//      itself compiles) can never silently omit a new file: adding a
//      header anywhere under src/ -- including inside a brand-new nested
//      subdirectory -- without also registering it in
//      ARKHAM_FOUNDATION_HEADERS fails CMake *configuration* outright,
//      via cmake/DomainHeaderInventory.cmake's
//      arkham_check_domain_header_inventory() FATAL_ERROR gate, before
//      this test binary is even built. See
//      tests/cmake/DomainHeaderInventoryPolicyTest.cmake for the
//      dedicated ctest case proving that gate itself works.
//   3. findViolations() below now also flags a conversion-operator
//      declaration targeting a banned type (`operator QJsonObject()
//      const;` and friends) as its own rule, alongside the pre-existing
//      return-type/trailing-return-type/alias/bare-auto rules --
//      matching the reviewer's exact reported example, without
//      generalizing to "detect every possible conversion operator" (this
//      codebase's UrlValidator.h/ValueOrError.h both have a genuine,
//      unrelated `explicit operator bool() const noexcept;`, which must
//      keep compiling).
//   4. Every scanned domain header is now also checked for any
//      `#define` directive at all (see macroDefinePattern()) and flagged
//      unconditionally if one is present. No current header needs one
//      (confirmed: zero pre-existing `#define` usage anywhere under
//      src/), so this closes the entire "hide a banned type behind a
//      macro alias" evasion vector -- for every rule, not just
//      return-type -- without needing real preprocessing/macro
//      expansion at all: if a domain header cannot define a macro, it
//      cannot rename a banned type via one either.
//
// Finally, the whole-file exemption for RawJson.h/JsonDecode.h/
// AuthModels.h is gone. Every header in arkhamDomainHeaderInventory() is
// scanned unconditionally now; a small, explicit, per-basename allowlist
// of *exact* expected violation text (pinnedExceptions() below) is
// consulted instead, so a *different* or *new* declaration appearing in
// one of those three files -- even one that looks superficially similar
// -- is still flagged, and the allowlist itself is asserted to contain no
// stale/orphaned entry that no longer matches anything real.
//
//   findViolations() strips block/line comments and string/char literals
//   (so neither can smuggle a false match, in either direction) and then
//   flags, anywhere in the remaining text:
//     (a) a same-line or multi-line "TYPE name(" / "ValueOrError<TYPE> name("
//         / "std::optional<TYPE> name(" return-type-then-name-then-paren
//         adjacency, for TYPE in {QJsonObject, QJsonArray, QJsonValue};
//     (b) a trailing "-> TYPE" return type, optionally wrapped the same way;
//     (c) a `using X = ...TYPE...;` / `typedef ... TYPE ...;` alias that
//         would let a banned type hide behind a new name;
//     (d) any bare deduced-`auto` function declaration with no trailing
//         `-> Type` at all;
//     (e) a conversion-operator declaration targeting a banned type
//         (`operator (const)? TYPE (`);
//     (f) any `#define` directive at all, anywhere in the file.
//
//   discoverHeaderFiles() recursively lists every *.h file under a
//   directory via QDirIterator at test run time; it is used only by the
//   scratch-directory mutation tests below (see
//   scannerFlagsANewlyAddedFileAutomatically() and
//   discoverHeaderFilesUtilityDiscoversNestedHeadersToo()), never by the
//   real policy check, which instead uses the CMake-generated,
//   build-verified arkhamDomainHeaderInventory() exclusively.
//
//   noDomainHeaderDeclaresAJsonReturningEncoder() applies findViolations()
//   to every header named by arkhamDomainHeaderInventory() with no file
//   skipped, and treats a violation as acceptable only if its exact
//   (basename, rule, snippet) triple appears in pinnedExceptions() --
//   see that function's own doc comment for why each entry is there.
class EncoderHygieneTests final : public QObject {
  Q_OBJECT

private slots:
  void noDomainHeaderDeclaresAJsonReturningEncoder();
  void pinnedExceptionAppliesOnlyToExactTriple();
  void pinnedExceptionDoesNotApplyUnderADifferentBasename();
  void pinnedExceptionRequiresExactTextNotFuzzyMatch();
  void productionRawJsonHeaderNoLongerDeclaresTheLossyMethod();
  void generatedInventoryListsRealAbsolutePathsIncludingRawJsonHeader();

  void scannerFlagsASameLineReturnTypeDeclaration();
  void scannerFlagsAValueOrErrorWrappedReturnTypeDeclaration();
  void scannerFlagsAnOptionalWrappedReturnTypeDeclaration();
  void scannerFlagsAMultiLineReturnTypeDeclaration();
  void scannerFlagsAnInlineReturnTypeDeclaration();
  void scannerFlagsATrailingReturnTypeDeclaration();
  void scannerFlagsATrailingValueOrErrorWrappedReturnTypeDeclaration();
  void scannerFlagsAUsingAliasOfABannedContainer();
  void scannerFlagsATypedefOfABannedContainer();
  void scannerFlagsABareDeducedAutoFunctionRegardlessOfItsBody();
  void scannerFlagsBothOverloadsSharingAName();
  void scannerFlagsANamespaceScopedFreeFunctionReturnType();
  void scannerFlagsADeclarationSplitByAnEmptyBlockComment();
  void scannerFlagsADeclarationSplitByAnEmptyLineComment();
  void scannerFlagsAReferenceReturnTypeDeclaration();
  void scannerFlagsAPointerReturnTypeDeclaration();
  void scannerFlagsAConversionOperatorToABannedType();
  void scannerIgnoresALegitimateBoolConversionOperator();
  void scannerFlagsAnyMacroDefineDirective();
  void scannerFlagsAMacroDefinedReturnTypeAliasViaTheOutrightDefineBan();
  void scannerIgnoresAPragmaOnceDirective();
  void scannerIgnoresALegitimateTrailingReturnType();
  void scannerIgnoresACommentMentioningABannedType();
  void scannerIgnoresAStringLiteralMentioningABannedType();
  void scannerIgnoresAByValueOrByRefParameterUsage();
  void scannerIgnoresAnUnnamedParameter();
  void scannerFlagsANewlyAddedFileAutomatically();
  void discoverHeaderFilesUtilityDiscoversNestedHeadersToo();
};

namespace {

struct Violation {
  QString file;
  int line = 0;
  QString rule;
  QString snippet;
};

QString describe(const Violation &v) {
  return u"%1:%2: [%3] %4"_s.arg(v.file).arg(v.line).arg(v.rule,
                                                         v.snippet.trimmed());
}

QString describeAll(const QList<Violation> &violations) {
  QStringList lines;
  lines.reserve(violations.size());
  for (const Violation &v : violations)
    lines.append(describe(v));
  return lines.join(u'\n');
}

// Comments and string/char literals are replaced with equal-length
// whitespace (preserving newlines, so downstream line numbers stay
// accurate) rather than deleted outright, so neither can ever
// contribute a false match in either direction: a banned type merely
// *mentioned* in prose or a literal cannot trip the scanner, and the
// scanner cannot be fooled into treating a real declaration as "just a
// comment" by a nearby unrelated one.
QString stripCommentsAndLiterals(const QString &source) {
  QString out;
  out.reserve(source.size());
  const qsizetype n = source.size();
  qsizetype i = 0;
  while (i < n) {
    const QChar c = source.at(i);
    if (c == u'/' && i + 1 < n && source.at(i + 1) == u'/') {
      // Every character of a "//" comment, including its own leading
      // delimiter, becomes a space -- not merely skipped -- so a
      // same-line comment with little or no content (e.g. "//") still
      // separates whatever tokens surrounded it by at least one space
      // after stripping, exactly as it did before stripping, rather
      // than only the comment's *content* becoming whitespace while its
      // delimiter silently vanishes and could concatenate the tokens
      // on either side of it.
      while (i < n && source.at(i) != u'\n') {
        out.append(u' ');
        ++i;
      }
      continue;
    }
    if (c == u'/' && i + 1 < n && source.at(i + 1) == u'*') {
      // Same principle for "/* */": both delimiters become whitespace
      // too, so an empty block comment ("/**/") between two tokens
      // still leaves 4 spaces of separation rather than 0 -- see
      // scannerFlagsADeclarationSplitByAnEmptyBlockComment() below,
      // which is exactly the false negative an unpatched version of
      // this function could produce.
      out.append(u' ');
      out.append(u' ');
      i += 2;
      while (i < n &&
             !(source.at(i) == u'*' && i + 1 < n && source.at(i + 1) == u'/')) {
        out.append(source.at(i) == u'\n' ? u'\n' : u' ');
        ++i;
      }
      if (i < n) {
        out.append(u' ');
        ++i;
      }
      if (i < n) {
        out.append(u' ');
        ++i;
      }
      continue;
    }
    if (c == u'"' || c == u'\'') {
      const QChar quote = c;
      out.append(u' ');
      ++i;
      while (i < n && source.at(i) != quote) {
        if (source.at(i) == u'\\' && i + 1 < n) {
          out.append(u' ');
          ++i;
        }
        out.append(source.at(i) == u'\n' ? u'\n' : u' ');
        ++i;
      }
      if (i < n) {
        out.append(u' ');
        ++i;
      }
      continue;
    }
    out.append(c);
    ++i;
  }
  return out;
}

int lineOf(const QString &strippedText, qsizetype pos) {
  return static_cast<int>(strippedText.left(pos).count(u'\n')) + 1;
}

QString snippetAt(const QString &strippedText, qsizetype start,
                  qsizetype length) {
  const qsizetype lineStart = strippedText.lastIndexOf(u'\n', start) + 1;
  qsizetype lineEnd = strippedText.indexOf(u'\n', start + length);
  if (lineEnd < 0)
    lineEnd = strippedText.size();
  return strippedText.mid(lineStart, lineEnd - lineStart).simplified();
}

// Matches a banned Qt JSON container name immediately followed (only
// whitespace, an optional generic-wrapper prefix/suffix, an optional
// `const`/reference/pointer return-type qualifier, and any number of
// closing '>' characters in between) by an identifier and its parameter
// list's opening '(' -- the textual shape of "this declaration's return
// type is (or wraps, or refers/points to) a banned type", independent of
// how many lines it spans and independent of a hidden body. A parameter
// usage such as `const QJsonValue &v` or `QJsonObject obj = QJsonObject()`
// never has an identifier *directly* followed by '(' immediately after
// the type name, so it cannot match this adjacency.
const QRegularExpression &returnTypePattern() {
  static const QRegularExpression re(
      uR"((?:(?:ValueOrError|std::optional)\s*<\s*)*\b(?:QJsonObject|QJsonArray|QJsonValue)\b\s*>*\s*(?:const\s*)?[&*]*\s*[A-Za-z_]\w*\s*\()"_s);
  return re;
}

const QRegularExpression &trailingReturnTypePattern() {
  static const QRegularExpression re(
      uR"(->\s*(?:(?:ValueOrError|std::optional)\s*<\s*)*\b(?:QJsonObject|QJsonArray|QJsonValue)\b)"_s);
  return re;
}

const QRegularExpression &aliasPattern() {
  static const QRegularExpression re(
      uR"((?:\busing\s+\w+\s*=|\btypedef\b)[^;]*\b(?:QJsonObject|QJsonArray|QJsonValue)\b[^;]*;)"_s);
  return re;
}

// A conversion-operator declaration whose target type is one of the
// three banned Qt JSON containers, e.g. `operator QJsonObject() const;`
// or `explicit operator QJsonArray() const noexcept;`. Deliberately
// narrow -- it matches only these three specific type names after the
// `operator` keyword, not "any conversion operator" -- because this
// codebase has genuine, unrelated conversion operators to other types
// (UrlValidator.h and ValueOrError.h both declare a legitimate
// `explicit operator bool() const noexcept;`, see
// scannerIgnoresALegitimateBoolConversionOperator() below) that must
// keep compiling. Reusing the exact same three-name list every other
// rule in this file already checks against means this closes the
// reported conversion-operator bypass without inventing a new general
// "detect every conversion operator" grammar.
const QRegularExpression &conversionOperatorPattern() {
  static const QRegularExpression re(
      uR"(\boperator\s+(?:const\s+)?(?:QJsonObject|QJsonArray|QJsonValue)\b\s*\()"_s);
  return re;
}

// Any `#define` preprocessor directive, anywhere in a domain header.
// Confirmed zero pre-existing usage across every header under src/ (see
// scannerFlagsAnyMacroDefineDirective()'s doc comment), so this is a
// zero-false-positive, unconditional ban -- not a narrowly-scoped
// allowlist -- that closes the entire "hide a banned type behind a
// macro alias" evasion vector for every rule above, not merely
// return-type, without needing real preprocessing/macro expansion: a
// header that cannot define a macro at all cannot rename a banned type
// via one either. MultilineOption is required for '^' to anchor at
// every line start rather than only the start of the whole (multi-line)
// stripped text.
const QRegularExpression &macroDefinePattern() {
  static const QRegularExpression re(uR"(^[ \t]*#\s*define\b)"_s,
                                     QRegularExpression::MultilineOption);
  return re;
}

// A bare deduced-return function declaration: `auto name(...)` with no
// trailing `-> Type` anywhere before the terminating ';' or '{'. The
// parameter list is allowed one level of nested parens (e.g. a function-
// pointer parameter) via the alternation below; this codebase's domain
// headers need nothing deeper.
const QRegularExpression &bareAutoPattern() {
  static const QRegularExpression re(
      uR"(\bauto\s+[A-Za-z_]\w*\s*\((?:[^()]|\([^()]*\))*\)\s*(?:const\s*)?(?:noexcept\b(?:\s*\([^()]*\))?\s*)?(?:override\s*)?(?:final\s*)?(?=;|\{)(?!\s*->))"_s);
  return re;
}

void collect(const QString &strippedText, const QString &fileLabel,
             const QRegularExpression &pattern, const QString &rule,
             QList<Violation> &out) {
  auto it = pattern.globalMatch(strippedText);
  while (it.hasNext()) {
    const QRegularExpressionMatch m = it.next();
    out.append(Violation{
        fileLabel, lineOf(strippedText, m.capturedStart()), rule,
        snippetAt(strippedText, m.capturedStart(), m.capturedLength())});
  }
}

// The one function every test below (including the real policy check)
// goes through -- there is exactly one code path from "raw header text"
// to "list of violations", so a mutation test proving a given shape is
// caught proves it is caught for the real src/ scan too.
QList<Violation> findViolations(const QString &fileLabel,
                                const QString &rawSource) {
  const QString stripped = stripCommentsAndLiterals(rawSource);
  QList<Violation> violations;
  collect(stripped, fileLabel, returnTypePattern(), u"return-type"_s,
          violations);
  collect(stripped, fileLabel, trailingReturnTypePattern(),
          u"trailing-return-type"_s, violations);
  collect(stripped, fileLabel, aliasPattern(), u"type-alias"_s, violations);
  collect(stripped, fileLabel, bareAutoPattern(), u"bare-auto"_s, violations);
  collect(stripped, fileLabel, conversionOperatorPattern(),
          u"conversion-operator"_s, violations);
  collect(stripped, fileLabel, macroDefinePattern(), u"macro-define"_s,
          violations);
  return violations;
}

QList<Violation> findViolationsInFile(const QString &path) {
  QFile file(path);
  if (!file.open(QIODevice::ReadOnly | QIODevice::Text))
    return {Violation{path, 0, u"unreadable"_s,
                      u"could not open file for reading"_s}};
  QTextStream stream(&file);
  return findViolations(path, stream.readAll());
}

// Every *.h file anywhere under dir, including nested subdirectories,
// discovered at run time (not a fixed list) via QDirIterator's recursive
// mode -- see discoverHeaderFilesUtilityDiscoversNestedHeadersToo() for
// the mutation test proving that recursion. Used ONLY by the
// scratch-directory mutation tests below
// (scannerFlagsANewlyAddedFileAutomatically() and that recursion test);
// the real policy check (noDomainHeaderDeclaresAJsonReturningEncoder())
// uses the CMake-generated arkhamDomainHeaderInventory() exclusively
// instead, so it can never itself regress into being non-recursive --
// there is no directory walk left in it at all.
QStringList discoverHeaderFiles(const QString &dir) {
  QStringList paths;
  QDirIterator it(dir, QStringList{u"*.h"_s}, QDir::Files,
                  QDirIterator::Subdirectories);
  while (it.hasNext())
    paths.append(it.next());
  paths.sort();
  return paths;
}

// One pinned, exact-text exception to the "no Qt-JSON-returning
// declaration" policy below. Matched by the exact (basename, rule,
// snippet) triple -- not by basename alone -- so a *different* or
// *newly added* declaration in the same file, even one that looks
// superficially similar, is still flagged; see
// pinnedExceptionAppliesOnlyToExactTriple() and
// pinnedExceptionRequiresExactTextNotFuzzyMatch().
struct PinnedException {
  QString basename;
  QString rule;
  QString snippet;
  QString justification;
};

// The complete, explicit allowlist of every Qt-JSON-returning
// declaration this codebase's domain headers are permitted to contain --
// replacing the previous whole-file exemption for RawJson.h/
// JsonDecode.h/AuthModels.h (which a cumulative review correctly flagged
// as still letting a *different*, newly-added declaration in one of
// those three files slip through unnoticed). Every header, including
// these three, is now scanned in full by
// noDomainHeaderDeclaresAJsonReturningEncoder() below; a violation is
// suppressed only when it exactly matches one of these entries.
//
// noDomainHeaderDeclaresAJsonReturningEncoder() additionally asserts
// every entry here is actually observed at least once in the real scan
// (never merely a stale, orphaned exception left over from a prior
// refactor), and only a "return-type" or "trailing-return-type" rule is
// ever eligible to be pinned -- a bare-auto/type-alias/conversion-
// operator/macro-define violation can never be suppressed this way, no
// matter what text it contains (see
// pinnedExceptionAppliesOnlyToExactTriple()).
const QList<PinnedException> &pinnedExceptions() {
  static const QList<PinnedException> exceptions = {
      // RawJson.h: the one production header allowed to convert a
      // validated raw Json::Value AST INTO a standard Qt JSON type.
      // These take no QJson-typed parameter at all -- they encode
      // *this, the already-validated raw AST, never an externally
      // constructed QJsonValue/QJsonObject/QJsonArray passed in -- and
      // are the sole sanctioned encode-direction adapters every other
      // domain header must compose with instead of building its own.
      {u"RawJson.h"_s, u"return-type"_s,
       u"[[nodiscard]] ValueOrError<QJsonValue> toExactQJson() const;"_s,
       u"the central exact AST-to-QJson adapter"_s},
      {u"RawJson.h"_s, u"return-type"_s,
       u"[[nodiscard]] ValueOrError<QJsonObject> toExactQJsonObject() const;"_s,
       u"the central exact AST-to-QJson adapter, QJsonObject-typed"_s},
      {u"RawJson.h"_s, u"return-type"_s,
       u"[[nodiscard]] ValueOrError<QJsonArray> toExactQJsonArray() const;"_s,
       u"the central exact AST-to-QJson adapter, QJsonArray-typed"_s},
      // toExactQJsonInner() is a *private* member function -- the
      // shared recursive body factored out of toExactQJson() above (see
      // its doc comment) so the three public adapters don't each
      // duplicate the same depth/duplicate-key/Undefined/surrogate/
      // ParseLimits-bounds walk. It enforces exactly the same
      // invariants as its public callers, is unreachable from any other
      // domain header (no friend grant, no public/protected access),
      // and cannot be called with anything other than an already-
      // validated Value's own private state -- it is part of the same
      // sanctioned adapter family, not a rival encode surface.
      {u"RawJson.h"_s, u"return-type"_s,
       u"[[nodiscard]] ValueOrError<QJsonValue> toExactQJsonInner(const ParseLimits &limits, int depth,"_s,
       u"private recursive body shared by the toExactQJson*() family above"_s},
      // The hidden-friend hook granting tests/RawJsonLossyTestOnly.h
      // (never compiled into the arkham_foundation production target --
      // see CMakeLists.txt) access to Value's private representation.
      // This line has NO body/definition anywhere in this production
      // header or any translation unit compiled into arkham_foundation;
      // it exists purely so a `friend` grant has a declaration to
      // attach to, and can only ever be found via argument-dependent
      // lookup on a Value argument. See its own doc comment, right
      // above this declaration inside class Value, for the full
      // rationale (this replaced an earlier `friend class
      // ::RawJsonTests;` whole-class grant plus a private
      // Value::toLossyQJsonForTestingOnly() member function, which a
      // cumulative review correctly flagged as a hidden lossy escape
      // hatch one `private:` -> `public:` edit away from being callable
      // from production code again).
      {u"RawJson.h"_s, u"return-type"_s,
       u"friend QJsonValue rawValueToLossyQJsonForTestingOnly(const Value &value);"_s,
       u"friend-grant-only declaration for the relocated test-only lossy helper; never defined/linked in the production header/target"_s},

      // JsonDecode.h: DECODE-direction helpers only -- every one of
      // these takes an existing QJsonValue/QJsonObject *in* (already
      // produced by Qt's own QJsonDocument parser at the one true
      // input boundary, see JsonDecode.cpp) and returns a narrowed
      // slice/view of that same already-parsed input, or a
      // std::optional/ValueOrError wrapping thereof -- never encoding
      // a domain value INTO new Qt JSON. None of these ever originates
      // a QJsonValue/QJsonObject/QJsonArray; they only ever hand back a
      // sub-object/sub-array/scalar that was already part of the
      // caller-supplied argument.
      {u"JsonDecode.h"_s, u"return-type"_s,
       u"[[nodiscard]] inline std::optional<QJsonValue> findField(const QJsonObject &obj, QLatin1StringView key) {"_s,
       u"decode-direction: returns a slice of the QJsonObject passed in, never originates one"_s},
      {u"JsonDecode.h"_s, u"return-type"_s,
       u"[[nodiscard]] ValueOrError<QJsonObject> requireObject(const QJsonValue &v,"_s,
       u"decode-direction: narrows an already-parsed QJsonValue to QJsonObject"_s},
      {u"JsonDecode.h"_s, u"return-type"_s,
       u"[[nodiscard]] ValueOrError<QJsonArray> requireArray(const QJsonValue &v,"_s,
       u"decode-direction: narrows an already-parsed QJsonValue to QJsonArray"_s},
      {u"JsonDecode.h"_s, u"return-type"_s,
       u"[[nodiscard]] ValueOrError<QJsonObject> requireObjectField(const QJsonObject &obj, QLatin1StringView key,"_s,
       u"decode-direction: returns a sub-object field of the QJsonObject passed in"_s},
      {u"JsonDecode.h"_s, u"return-type"_s,
       u"[[nodiscard]] ValueOrError<QJsonArray> requireArrayField(const QJsonObject &obj,"_s,
       u"decode-direction: returns a sub-array field of the QJsonObject passed in"_s},
      {u"JsonDecode.h"_s, u"return-type"_s,
       u"[[nodiscard]] ValueOrError<QJsonValue> requireRawField(const QJsonObject &obj,"_s,
       u"decode-direction: returns a raw field slice of the QJsonObject passed in"_s},
      {u"JsonDecode.h"_s, u"return-type"_s,
       u"[[nodiscard]] ValueOrError<QJsonValue> optionalRawArrayField(const QJsonObject &obj, QLatin1StringView key,"_s,
       u"decode-direction: returns an optional raw array field slice of the QJsonObject passed in"_s},
      {u"JsonDecode.h"_s, u"return-type"_s,
       u"[[nodiscard]] ValueOrError<QJsonValue> optionalRawObjectField(const QJsonObject &obj, QLatin1StringView key,"_s,
       u"decode-direction: returns an optional raw object field slice of the QJsonObject passed in"_s},
      {u"JsonDecode.h"_s, u"return-type"_s,
       u"[[nodiscard]] QList<std::pair<QString, QJsonValue>> objectMembers(const QJsonObject &obj);"_s,
       u"decode-direction: enumerates the members of the QJsonObject passed in, values unchanged"_s},

      // AuthModels.h: pre-existing, out-of-scope networking/auth request
      // encoders (see NetworkAuthenticationClient.cpp), unrelated to
      // issue #19's CardCatalog/Decks/Games/Identifiers domain model and
      // deliberately left alone by this PR's scope. Both
      // AuthenticateRequest::toJson() and RegisterRequest::toJson()
      // share this identical signature text; isPinnedException() always
      // credits the first pin whose (basename, rule, snippet) triple
      // matches, so two separate pins with identical text can never
      // each independently accrue a match (the second would always
      // register as stale) -- one pin covering both real declarations
      // is therefore correct here, not an oversight.
      {u"AuthModels.h"_s, u"return-type"_s,
       u"[[nodiscard]] QJsonObject toJson() const;"_s,
       u"AuthenticateRequest::toJson() and RegisterRequest::toJson(), pre-existing out-of-scope auth encoders sharing identical signature text"_s},
  };
  return exceptions;
}

bool isPinnedException(const Violation &v, const QList<PinnedException> &pins,
                       QList<int> *matchedIndices = nullptr) {
  const QString basename = QFileInfo(v.file).fileName();
  // Only these two rules can ever be pinned -- see pinnedExceptions()'s
  // own doc comment.
  if (v.rule != u"return-type"_s && v.rule != u"trailing-return-type"_s)
    return false;
  for (qsizetype i = 0; i < pins.size(); ++i) {
    const PinnedException &p = pins[i];
    if (p.basename == basename && p.rule == v.rule && p.snippet == v.snippet) {
      if (matchedIndices)
        matchedIndices->append(static_cast<int>(i));
      return true;
    }
  }
  return false;
}

QString writeTempHeader(QTemporaryDir &dir, const QString &relativePath,
                        const QString &content) {
  const QString path = dir.filePath(relativePath);
  QFileInfo info(path);
  const bool mkpathOk = QDir().mkpath(info.absolutePath());
  Q_ASSERT(mkpathOk);
  QFile file(path);
  const bool opened = file.open(QIODevice::WriteOnly | QIODevice::Text);
  Q_ASSERT(opened);
  QTextStream stream(&file);
  stream << content;
  return path;
}

} // namespace

// --- The real policy, applied to this repository's actual src/ headers ---

void EncoderHygieneTests::noDomainHeaderDeclaresAJsonReturningEncoder() {
  const QStringList headers = arkhamDomainHeaderInventory();
  QVERIFY2(headers.size() > 30,
           "expected the CMake-generated header inventory (see "
           "CMakeLists.txt's configure_file(tests/DomainHeaderInventory.h.in "
           "...)) to list the full src/ header set; generation may be "
           "broken");

  const QList<PinnedException> pins = pinnedExceptions();
  QList<int> matchCounts(pins.size(), 0);

  QList<Violation> unexpected;
  for (const QString &path : headers) {
    QVERIFY2(
        QFileInfo::exists(path),
        qPrintable(u"generated header inventory names a file that does "
                   "not exist on disk: %1 -- see CMakeLists.txt's "
                   "arkham_check_domain_header_inventory() gate"_s.arg(path)));
    for (const Violation &v : findViolationsInFile(path)) {
      QList<int> matched;
      if (isPinnedException(v, pins, &matched)) {
        for (int idx : matched)
          ++matchCounts[idx];
      } else {
        unexpected.append(v);
      }
    }
  }

  QVERIFY2(
      unexpected.isEmpty(),
      qPrintable(
          u"public Qt-JSON-returning (or macro-defining, or "
          "conversion-operator-to-a-banned-type) declaration(s) found in "
          "domain headers with no exact pinned justification -- domain "
          "values must expose only toRawJson()/toJsonBytes() and compose "
          "with the central Value::toExactQJson() family instead. If this "
          "is a genuinely new, reviewed, narrowly-scoped adapter, add an "
          "exact-text entry to pinnedExceptions() naming it explicitly; do "
          "not widen any existing rule/regex to accommodate it:\n%1"_s.arg(
              describeAll(unexpected))));

  QStringList stalePins;
  for (qsizetype i = 0; i < pins.size(); ++i) {
    if (matchCounts[i] == 0)
      stalePins.append(u"%1 [%2] %3 (%4)"_s.arg(pins[i].basename, pins[i].rule,
                                                pins[i].snippet,
                                                pins[i].justification));
  }
  QVERIFY2(
      stalePins.isEmpty(),
      qPrintable(
          u"pinnedExceptions() contains an entry that no longer matches any "
          "real declaration in the scanned headers (a stale/orphaned "
          "allowlist entry, most likely left over from a prior refactor) -- "
          "remove it:\n%1"_s.arg(stalePins.join(u'\n'))));
}

void EncoderHygieneTests::pinnedExceptionAppliesOnlyToExactTriple() {
  const QList<PinnedException> pins = {
      {u"Fake.h"_s, u"return-type"_s, u"QJsonObject toJson() const;"_s,
       u"test fixture"_s},
  };
  const Violation matching{u"Fake.h"_s, 1, u"return-type"_s,
                           u"QJsonObject toJson() const;"_s};
  const Violation differentText{u"Fake.h"_s, 1, u"return-type"_s,
                                u"QJsonObject toJsonDifferent() const;"_s};
  const Violation differentBasename{u"Other.h"_s, 1, u"return-type"_s,
                                    u"QJsonObject toJson() const;"_s};
  // Same exact text, but under a rule that must never be pinnable
  // regardless of its snippet -- a bare-auto/type-alias/
  // conversion-operator/macro-define violation can never be suppressed
  // by any pinned exception, no matter what text it happens to contain.
  const Violation differentRule{u"Fake.h"_s, 1, u"bare-auto"_s,
                                u"QJsonObject toJson() const;"_s};

  QVERIFY(isPinnedException(matching, pins));
  QVERIFY(!isPinnedException(differentText, pins));
  QVERIFY(!isPinnedException(differentBasename, pins));
  QVERIFY(!isPinnedException(differentRule, pins));
}

void EncoderHygieneTests::pinnedExceptionDoesNotApplyUnderADifferentBasename() {
  const QList<PinnedException> pins = pinnedExceptions();
  QVERIFY(!pins.isEmpty());
  const PinnedException &first = pins.first();
  const Violation elsewhere{u"SomewhereElse.h"_s, 1, first.rule, first.snippet};
  QVERIFY(!isPinnedException(elsewhere, pins));
}

void EncoderHygieneTests::pinnedExceptionRequiresExactTextNotFuzzyMatch() {
  const QList<PinnedException> pins = pinnedExceptions();
  const auto it =
      std::find_if(pins.begin(), pins.end(), [](const PinnedException &p) {
        return p.basename == u"RawJson.h"_s;
      });
  QVERIFY(it != pins.end());
  // One trailing space is enough to defeat the match: this is an exact
  // string comparison, never a prefix/substring/fuzzy check.
  const Violation almostIdentical{u"RawJson.h"_s, 1, it->rule,
                                  it->snippet + u" "_s};
  QVERIFY(!isPinnedException(almostIdentical, pins));
}

void EncoderHygieneTests::
    productionRawJsonHeaderNoLongerDeclaresTheLossyMethod() {
  // Direct proof of the reported bypass's fix: the lossy conversion no
  // longer exists anywhere in this production header -- as a method
  // name, public or private -- for a `private:` -> `public:` edit to
  // ever reveal. (Its relocated free-function counterpart still exists,
  // but only in tests/RawJsonLossyTestOnly.h, which is never part of
  // arkhamDomainHeaderInventory() -- see CMakeLists.txt's
  // ARKHAM_FOUNDATION_HEADERS, which lists only src/*.h.)
  const QStringList headers = arkhamDomainHeaderInventory();
  const auto it =
      std::find_if(headers.begin(), headers.end(), [](const QString &path) {
        return QFileInfo(path).fileName() == u"RawJson.h"_s;
      });
  QVERIFY(it != headers.end());
  QFile file(*it);
  QVERIFY(file.open(QIODevice::ReadOnly | QIODevice::Text));
  const QString content = QString::fromUtf8(file.readAll());
  QVERIFY2(!content.contains(u"toLossyQJsonForTestingOnly"_s),
           "RawJson.h must not mention toLossyQJsonForTestingOnly at all -- "
           "it was relocated to tests/RawJsonLossyTestOnly.h");
}

void EncoderHygieneTests::
    generatedInventoryListsRealAbsolutePathsIncludingRawJsonHeader() {
  const QStringList headers = arkhamDomainHeaderInventory();
  const bool anyIsRawJson =
      std::any_of(headers.begin(), headers.end(), [](const QString &path) {
        return QFileInfo(path).fileName() == u"RawJson.h"_s &&
               QFileInfo(path).isAbsolute() && QFileInfo::exists(path);
      });
  QVERIFY(anyIsRawJson);
}

// --- Mutation tests: each proves one specific evasion vector still gets
//     caught (or, for the negative cases, is correctly never flagged) ---

void EncoderHygieneTests::scannerFlagsASameLineReturnTypeDeclaration() {
  const auto v = findViolations(
      u"T.h"_s, u"  [[nodiscard]] QJsonObject toJson() const;\n"_s);
  QCOMPARE(v.size(), 1);
  QCOMPARE(v.first().rule, u"return-type"_s);
}

void EncoderHygieneTests::
    scannerFlagsAValueOrErrorWrappedReturnTypeDeclaration() {
  const auto v = findViolations(
      u"T.h"_s,
      u"  [[nodiscard]] ValueOrError<QJsonArray> toRows() const;\n"_s);
  QCOMPARE(v.size(), 1);
  QCOMPARE(v.first().rule, u"return-type"_s);
}

void EncoderHygieneTests::scannerFlagsAnOptionalWrappedReturnTypeDeclaration() {
  const auto v = findViolations(
      u"T.h"_s,
      u"  [[nodiscard]] std::optional<QJsonValue> maybeRaw() const;\n"_s);
  QCOMPARE(v.size(), 1);
  QCOMPARE(v.first().rule, u"return-type"_s);
}

void EncoderHygieneTests::scannerFlagsAMultiLineReturnTypeDeclaration() {
  const auto v = findViolations(
      u"T.h"_s,
      u"[[nodiscard]] QJsonObject\nencodeGameList(const QList<GameListRow> &rows);\n"_s);
  QCOMPARE(v.size(), 1);
  QCOMPARE(v.first().rule, u"return-type"_s);
}

void EncoderHygieneTests::scannerFlagsAnInlineReturnTypeDeclaration() {
  // Explicit regression for the reviewer's named "inline" mutation
  // vector: the `inline` keyword before the return type does not shift
  // where the match starts (it begins at the banned type name itself),
  // so an inline function definition is caught exactly like a plain
  // declaration.
  const auto v = findViolations(
      u"T.h"_s,
      u"  inline QJsonObject toJson() const { return QJsonObject(); }\n"_s);
  QCOMPARE(v.size(), 1);
  QCOMPARE(v.first().rule, u"return-type"_s);
}

void EncoderHygieneTests::scannerFlagsATrailingReturnTypeDeclaration() {
  const auto v = findViolations(
      u"T.h"_s, u"  [[nodiscard]] auto toJson() const -> QJsonObject;\n"_s);
  // A bare-shape return-type match and the dedicated trailing-return-type
  // rule both legitimately see this (the identifier before '->' also
  // happens not to precede '(' directly, so only the trailing rule fires
  // here); assert on the trailing rule specifically being present.
  const bool sawTrailing =
      std::any_of(v.begin(), v.end(), [](const Violation &x) {
        return x.rule == u"trailing-return-type"_s;
      });
  QVERIFY(sawTrailing);
}

void EncoderHygieneTests::
    scannerFlagsATrailingValueOrErrorWrappedReturnTypeDeclaration() {
  const auto v = findViolations(
      u"T.h"_s,
      u"  [[nodiscard]] auto toRows() const -> ValueOrError<QJsonArray>;\n"_s);
  const bool sawTrailing =
      std::any_of(v.begin(), v.end(), [](const Violation &x) {
        return x.rule == u"trailing-return-type"_s;
      });
  QVERIFY(sawTrailing);
}

void EncoderHygieneTests::scannerFlagsAUsingAliasOfABannedContainer() {
  const auto v = findViolations(u"T.h"_s, u"using JsonMap = QJsonObject;\n"_s);
  QCOMPARE(v.size(), 1);
  QCOMPARE(v.first().rule, u"type-alias"_s);
}

void EncoderHygieneTests::scannerFlagsATypedefOfABannedContainer() {
  const auto v = findViolations(u"T.h"_s, u"typedef QJsonArray JsonList;\n"_s);
  QCOMPARE(v.size(), 1);
  QCOMPARE(v.first().rule, u"type-alias"_s);
}

void EncoderHygieneTests::
    scannerFlagsABareDeducedAutoFunctionRegardlessOfItsBody() {
  // No banned type name appears in the text at all; only the bare-auto
  // shape itself is enough to flag this, since the return type is
  // entirely hidden by deduction and this codebase's domain headers have
  // no legitimate need for that.
  const auto v =
      findViolations(u"T.h"_s, u"  auto toJson() const { return 5; }\n"_s);
  QCOMPARE(v.size(), 1);
  QCOMPARE(v.first().rule, u"bare-auto"_s);
}

void EncoderHygieneTests::scannerFlagsBothOverloadsSharingAName() {
  // The reported bypass: an overload sharing a name with an already-known
  // declaration must not be collapsed/deduped by any file#type#name-style
  // identity. There is no such identity key anywhere in this scanner --
  // every matched occurrence is reported independently.
  const auto v =
      findViolations(u"T.h"_s, u"  QJsonObject toJson() const;\n"
                               "  QJsonObject toJson(bool legacy) const;\n"_s);
  QCOMPARE(v.size(), 2);
}

void EncoderHygieneTests::scannerFlagsANamespaceScopedFreeFunctionReturnType() {
  // Explicit regression for the reviewer's named "namespace/free
  // function" mutation vector: the return-type rule requires no
  // enclosing class at all, so a free function declared inside a
  // namespace is caught identically to a member function.
  const auto v = findViolations(
      u"T.h"_s, u"namespace Arkham::Json::Extra {\n"
                u"[[nodiscard]] QJsonObject encode(const Value &value);\n"
                u"}\n"_s);
  QCOMPARE(v.size(), 1);
  QCOMPARE(v.first().rule, u"return-type"_s);
}

void EncoderHygieneTests::scannerFlagsADeclarationSplitByAnEmptyBlockComment() {
  // A prior version of stripCommentsAndLiterals() silently skipped a
  // block comment's own "/*"/"*/" delimiters instead of turning them
  // into whitespace like the rest of the comment; for a short/empty
  // comment this could concatenate the return type and the name into a
  // single token ("QJsonObjecttoJson"), which the \b-bounded return-type
  // regex would then fail to match -- a genuine false negative for
  // otherwise-valid, declaration-splitting C++ like
  // `QJsonObject/**/toJson()`. Every character of both delimiters must
  // become whitespace so the boundary is always preserved.
  const auto v =
      findViolations(u"T.h"_s, u"  QJsonObject/**/toJson() const;\n"_s);
  QCOMPARE(v.size(), 1);
  QCOMPARE(v.first().rule, u"return-type"_s);

  const auto withContent =
      findViolations(u"T.h"_s, u"  QJsonObject/*x*/toJson() const;\n"_s);
  QCOMPARE(withContent.size(), 1);
  QCOMPARE(withContent.first().rule, u"return-type"_s);
}

void EncoderHygieneTests::scannerFlagsADeclarationSplitByAnEmptyLineComment() {
  // Same principle for "//": its own delimiter must become whitespace,
  // not vanish, even though a trailing "//" comment always runs to the
  // (separately preserved) newline in practice and so this specific form
  // did not previously reproduce the bug -- kept as an explicit parity
  // regression for the sibling block-comment fix.
  const auto v =
      findViolations(u"T.h"_s, u"  QJsonObject//\n  toJson() const;\n"_s);
  QCOMPARE(v.size(), 1);
  QCOMPARE(v.first().rule, u"return-type"_s);
}

void EncoderHygieneTests::scannerFlagsAReferenceReturnTypeDeclaration() {
  // Reported gap: a banned type returned by reference (or rvalue
  // reference) breaks the plain "type-then-whitespace-then-name"
  // adjacency the original regex required, letting it slip past
  // undetected even though it is exactly the same prohibited return
  // type. The qualifier is now tolerated between the type and the name.
  const auto lvalueRef =
      findViolations(u"T.h"_s, u"  QJsonObject& mutableJson();\n"_s);
  QCOMPARE(lvalueRef.size(), 1);
  QCOMPARE(lvalueRef.first().rule, u"return-type"_s);

  const auto rvalueRef =
      findViolations(u"T.h"_s, u"  ValueOrError<QJsonArray>&& takeRows();\n"_s);
  QCOMPARE(rvalueRef.size(), 1);
  QCOMPARE(rvalueRef.first().rule, u"return-type"_s);
}

void EncoderHygieneTests::scannerFlagsAPointerReturnTypeDeclaration() {
  const auto v =
      findViolations(u"T.h"_s, u"  const QJsonValue* g() const;\n"_s);
  QCOMPARE(v.size(), 1);
  QCOMPARE(v.first().rule, u"return-type"_s);
}

void EncoderHygieneTests::scannerFlagsAConversionOperatorToABannedType() {
  // The reported bypass: a conversion operator entirely evades the
  // return-type-then-name-then-paren adjacency the other rules look for
  // (there is no name at all -- the "name" grammatically *is* the
  // target type). A dedicated rule closes exactly this shape.
  const auto plain =
      findViolations(u"T.h"_s, u"  operator QJsonObject() const;\n"_s);
  QCOMPARE(plain.size(), 1);
  QCOMPARE(plain.first().rule, u"conversion-operator"_s);

  const auto explicitConst = findViolations(
      u"T.h"_s, u"  explicit operator QJsonArray() const noexcept;\n"_s);
  const bool sawConversion = std::any_of(
      explicitConst.begin(), explicitConst.end(),
      [](const Violation &x) { return x.rule == u"conversion-operator"_s; });
  QVERIFY(sawConversion);

  const auto valueOperator =
      findViolations(u"T.h"_s, u"  operator QJsonValue() const;\n"_s);
  QCOMPARE(valueOperator.size(), 1);
  QCOMPARE(valueOperator.first().rule, u"conversion-operator"_s);
}

void EncoderHygieneTests::scannerIgnoresALegitimateBoolConversionOperator() {
  // UrlValidator.h and ValueOrError.h both declare a genuine, unrelated
  // `explicit operator bool() const noexcept;` -- the conversion-
  // operator rule targets only the three banned Qt JSON container
  // names, never "any conversion operator", so this must keep compiling
  // unflagged.
  const auto v = findViolations(
      u"T.h"_s, u"  explicit operator bool() const noexcept;\n"_s);
  QVERIFY(v.isEmpty());
}

void EncoderHygieneTests::scannerFlagsAnyMacroDefineDirective() {
  // Confirmed (at the time this rule was added) zero pre-existing
  // `#define` usage anywhere under src/*.h, so this is an unconditional,
  // zero-false-positive ban -- not merely a rule targeting banned-type
  // aliases specifically.
  const auto v =
      findViolations(u"T.h"_s, u"#define SOME_UNRELATED_CONSTANT 5\n"_s);
  QCOMPARE(v.size(), 1);
  QCOMPARE(v.first().rule, u"macro-define"_s);

  const auto indented =
      findViolations(u"T.h"_s, u"  #  define INDENTED_TOO 1\n"_s);
  QCOMPARE(indented.size(), 1);
  QCOMPARE(indented.first().rule, u"macro-define"_s);
}

void EncoderHygieneTests::
    scannerFlagsAMacroDefinedReturnTypeAliasViaTheOutrightDefineBan() {
  // The reported bypass: `#define JSON_RESULT QJsonObject` followed by
  // `JSON_RESULT toJson() const;` -- the return-type regex operates on
  // raw source text, not preprocessor-expanded text, so it cannot see
  // through "JSON_RESULT" to "QJsonObject" (and this file deliberately
  // does not attempt real macro expansion, having judged that
  // impractical/fragile for CI -- see this file's class doc comment).
  // The declaration line itself is therefore NOT expected to trip the
  // return-type rule. What *does* catch this evasion is the
  // unconditional macro-define ban: the `#define` line is flagged
  // outright, regardless of what it defines or how its result is later
  // used.
  const auto v = findViolations(
      u"T.h"_s, u"#define JSON_RESULT QJsonObject\n"
                u"  [[nodiscard]] JSON_RESULT toJson() const;\n"_s);
  const bool sawMacroDefine =
      std::any_of(v.begin(), v.end(), [](const Violation &x) {
        return x.rule == u"macro-define"_s;
      });
  QVERIFY(sawMacroDefine);
}

void EncoderHygieneTests::scannerIgnoresAPragmaOnceDirective() {
  // Every real domain header begins with "#pragma once"; the
  // macro-define ban must never flag it (a different keyword --
  // "pragma", not "define" -- follows '#').
  const auto v = findViolations(u"T.h"_s, u"#pragma once\n"_s);
  QVERIFY(v.isEmpty());
}

void EncoderHygieneTests::scannerIgnoresALegitimateTrailingReturnType() {
  const auto v = findViolations(
      u"T.h"_s, u"  [[nodiscard]] auto toRawJson() const -> Json::Value;\n"_s);
  QVERIFY(v.isEmpty());
}

void EncoderHygieneTests::scannerIgnoresACommentMentioningABannedType() {
  const auto v = findViolations(
      u"T.h"_s,
      u"  // Historically this returned QJsonObject toJson() const; not any more.\n"_s);
  QVERIFY(v.isEmpty());
}

void EncoderHygieneTests::scannerIgnoresAStringLiteralMentioningABannedType() {
  const auto v = findViolations(
      u"T.h"_s, u"  const char *note = \"QJsonObject toJson() const;\";\n"_s);
  QVERIFY(v.isEmpty());
}

void EncoderHygieneTests::scannerIgnoresAByValueOrByRefParameterUsage() {
  const auto v = findViolations(
      u"T.h"_s, u"  [[nodiscard]] static ValueOrError<CardDef> fromJson(const "
                u"QJsonValue &v, "
                "QStringView path);\n"
                "  void accept(QJsonObject obj = QJsonObject());\n"_s);
  QVERIFY(v.isEmpty());
}

void EncoderHygieneTests::scannerIgnoresAnUnnamedParameter() {
  const auto v = findViolations(u"T.h"_s, u"  void accept(QJsonObject);\n"_s);
  QVERIFY(v.isEmpty());
}

void EncoderHygieneTests::scannerFlagsANewlyAddedFileAutomatically() {
  // Proves this shared low-level utility function's own dynamic
  // discovery against a scratch directory (never mutating the real
  // src/ tree): a file this test has never named before is still found
  // by discoverHeaderFiles() and scanned. This utility now backs only
  // scratch-directory mutation tests like this one -- the *real* policy
  // check (noDomainHeaderDeclaresAJsonReturningEncoder()) instead uses
  // the CMake-generated, build-verified arkhamDomainHeaderInventory()
  // exclusively (see tests/cmake/DomainHeaderInventoryPolicyTest.cmake
  // for the dedicated proof that a real new/nested/unregistered header
  // fails CMake configuration itself, independent of anything in this
  // file).
  QTemporaryDir dir;
  QVERIFY(dir.isValid());
  writeTempHeader(dir, u"AlreadyClean.h"_s,
                  u"class Clean { public: int value() const; };\n"_s);
  const QString badPath = writeTempHeader(
      dir, u"BrandNewFile.h"_s,
      u"class New { public: QJsonObject toJson() const; };\n"_s);

  const QStringList discovered = discoverHeaderFiles(dir.path());
  QVERIFY(discovered.contains(badPath));

  QList<Violation> violations;
  for (const QString &path : discovered)
    violations.append(findViolationsInFile(path));
  QCOMPARE(violations.size(), 1);
  QCOMPARE(violations.first().file, badPath);
}

void EncoderHygieneTests::
    discoverHeaderFilesUtilityDiscoversNestedHeadersToo() {
  // The specific gap a cumulative review named against the *old*
  // real-policy discovery function (QDir::entryList() without
  // QDir::Files-only, non-recursive): a header placed in a brand-new
  // nested subdirectory was never visited at all. discoverHeaderFiles()
  // now uses QDirIterator::Subdirectories and is proven recursive here,
  // directly against a scratch tree; the real policy check no longer
  // uses this function at all (see arkhamDomainHeaderInventory()), but
  // there is no reason for the shared utility itself to regress back to
  // being non-recursive either.
  QTemporaryDir dir;
  QVERIFY(dir.isValid());
  const QString nestedBadPath = writeTempHeader(
      dir, u"nested/deeper/BrandNewNestedFile.h"_s,
      u"class New { public: QJsonObject toJson() const; };\n"_s);

  const QStringList discovered = discoverHeaderFiles(dir.path());
  QVERIFY(discovered.contains(nestedBadPath));

  const QList<Violation> violations = findViolationsInFile(nestedBadPath);
  QCOMPARE(violations.size(), 1);
  QCOMPARE(violations.first().rule, u"return-type"_s);
}

QTEST_MAIN(EncoderHygieneTests)
#include "EncoderHygieneTests.moc"
